# Generated by Django 5.2 on 2026-02-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsRLD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='confidence_rice',
        ),
        migrations.RemoveField(
            model_name='systemstatistics',
            name='total_rice',
        ),
    ]
