# Generated by Django 5.2 on 2026-02-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsRLD', '0002_remove_diagnosisresult_confidence_rice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecategory',
            name='name',
            field=models.CharField(choices=[('bacterial_blight', 'Bacterial Leaf Blight'), ('rice_blast', 'Rice Blast'), ('tungro', 'Tungro'), ('healthy', 'Healthy')], max_length=50, unique=True, verbose_name='Nama Penyakit'),
        ),
    ]
