# Generated by Django 5.2 on 2026-03-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsRLD', '0003_alter_diseasecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraininghistory',
            name='per_class_metrics',
            field=models.JSONField(blank=True, help_text='JSON: {class_name: {precision, recall, f1, support}}', null=True, verbose_name='Metrik per Kelas'),
        ),
        migrations.AddField(
            model_name='modeltraininghistory',
            name='val_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='Akurasi Validasi (%)'),
        ),
    ]
